
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moklet
 */
public class lihat1 extends javax.swing.JFrame {

    /**
     * Creates new form buat
     */
    public lihat1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tanggal2 = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        isi = new javax.swing.JTextArea();
        tanggal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nana.png"))); // NOI18N
        jLabel5.setText("jLabel2");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nana.png"))); // NOI18N
        jLabel6.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Beyond The Mountains", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cute Diary");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(270, 510, 120, 40);

        jLabel2.setFont(new java.awt.Font("Beyond The Mountains", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Date");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 30, 70, 30);

        jLabel3.setFont(new java.awt.Font("Beyond The Mountains", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("How your feel today?");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 180, 140, 30);

        jLabel4.setFont(new java.awt.Font("Beyond The Mountains", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Subject");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 90, 70, 30);

        tanggal2.setText("Mau Curhat Perasaan Nih !");
        tanggal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tanggal2ActionPerformed(evt);
            }
        });
        jPanel1.add(tanggal2);
        tanggal2.setBounds(30, 120, 340, 30);

        simpan.setBackground(new java.awt.Color(255, 255, 255));
        simpan.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        simpan.setForeground(new java.awt.Color(204, 204, 255));
        simpan.setText("Finish");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel1.add(simpan);
        simpan.setBounds(10, 510, 250, 30);

        isi.setColumns(20);
        isi.setRows(5);
        isi.setText("Hatiku sangat Gundah.");
        jScrollPane1.setViewportView(isi);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 210, 350, 280);

        tanggal.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        tanggal.setForeground(new java.awt.Color(255, 255, 255));
        tanggal.setText("10/04/2017");
        jPanel1.add(tanggal);
        tanggal.setBounds(30, 60, 300, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nana.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(110, -220, 550, 630);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nana.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(-330, 320, 620, 630);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 390, 550);

        setSize(new java.awt.Dimension(406, 589));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed

            new lihat().show();
                this.dispose();
       /* if("".equals(tanggal2.getText())|| "".equals(isi.getText())){
           JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Warning", JOptionPane.WARNING_MESSAGE);
           }else{
             String SQL = "INSERT INTO `tb_diary`(`date`, `subject`, `curhat`) VALUES ('"+tanggal+"','"+tanggal2.getText()+"','"+isi.getText()+"') ;";
       int status = KoneksiDB.execute(SQL);
       if (status == 1){
           JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","OK", JOptionPane.INFORMATION_MESSAGE);
           selectData();  
       }
       else{
           JOptionPane.showMessageDialog(this,"Data gagal ditambahkan!","Warning",JOptionPane.WARNING_MESSAGE);
            }  
               
           
       }*/
        
        
    }//GEN-LAST:event_simpanActionPerformed

    private void tanggal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tanggal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tanggal2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(buat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new buat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea isi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JLabel tanggal;
    private javax.swing.JTextField tanggal2;
    // End of variables declaration//GEN-END:variables

  

    private void selectData() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
